// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @enum
 */
export enum CommandType{
  NONE= 0,
  Gucci= 1,
  Prada= 2
};

/**
 * @constructor
 */
export class Commander {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Commander
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Commander {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Commander= obj
 * @returns Commander
 */
static getRootAsCommander(bb:flatbuffers.ByteBuffer, obj?:Commander):Commander {
  return (obj || new Commander).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns CommandType
 */
cmdType():CommandType {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : CommandType.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
cmd<T extends flatbuffers.Table>(obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startCommander(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param CommandType cmdType
 */
static addCmdType(builder:flatbuffers.Builder, cmdType:CommandType) {
  builder.addFieldInt8(0, cmdType, CommandType.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset cmdOffset
 */
static addCmd(builder:flatbuffers.Builder, cmdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, cmdOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endCommander(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishCommanderBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

}
/**
 * @constructor
 */
export class Gucci {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Gucci
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Gucci {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Gucci= obj
 * @returns Gucci
 */
static getRootAsGucci(bb:flatbuffers.ByteBuffer, obj?:Gucci):Gucci {
  return (obj || new Gucci).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
gucci():string|null
gucci(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
gucci(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startGucci(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset gucciOffset
 */
static addGucci(builder:flatbuffers.Builder, gucciOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, gucciOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endGucci(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class Prada {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Prada
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Prada {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Prada= obj
 * @returns Prada
 */
static getRootAsPrada(bb:flatbuffers.ByteBuffer, obj?:Prada):Prada {
  return (obj || new Prada).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
prada():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startPrada(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param number prada
 */
static addPrada(builder:flatbuffers.Builder, prada:number) {
  builder.addFieldInt32(0, prada, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endPrada(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
